// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRFp1lNQCikOtejzB4sMKXigP4LFV-eY',
    appId: '1:889542269155:web:0ed69836d8156cba2d4dd6',
    messagingSenderId: '889542269155',
    projectId: 'bussiness-app-c4be7',
    authDomain: 'bussiness-app-c4be7.firebaseapp.com',
    databaseURL: 'https://bussiness-app-c4be7-default-rtdb.firebaseio.com',
    storageBucket: 'bussiness-app-c4be7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRq7NHTN-C6Ch-sy_Rm6bWjaWJzlfVEQ',
    appId: '1:889542269155:android:134d99826324e3102d4dd6',
    messagingSenderId: '889542269155',
    projectId: 'bussiness-app-c4be7',
    databaseURL: 'https://bussiness-app-c4be7-default-rtdb.firebaseio.com',
    storageBucket: 'bussiness-app-c4be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtIFtlxjifHYZAw7y0aQEMh18AwJUNzw',
    appId: '1:889542269155:ios:6c813ee3a53d156b2d4dd6',
    messagingSenderId: '889542269155',
    projectId: 'bussiness-app-c4be7',
    databaseURL: 'https://bussiness-app-c4be7-default-rtdb.firebaseio.com',
    storageBucket: 'bussiness-app-c4be7.appspot.com',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCtIFtlxjifHYZAw7y0aQEMh18AwJUNzw',
    appId: '1:889542269155:ios:17e11f97f7e8f1752d4dd6',
    messagingSenderId: '889542269155',
    projectId: 'bussiness-app-c4be7',
    databaseURL: 'https://bussiness-app-c4be7-default-rtdb.firebaseio.com',
    storageBucket: 'bussiness-app-c4be7.appspot.com',
    iosBundleId: 'com.example.businessApp.RunnerTests',
  );
}
